services:
  anteiku_kohi_database:
    image: postgres:latest
    container_name: anteiku_kohi_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: anteiku_kohi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d anteiku_kohi"]
      interval: 10s
      retries: 5
      start_period: 30s

  anteiku_kohi:
    build: .
    container_name: anteiku_kohi
    restart: unless-stopped
    depends_on:
      anteiku_kohi_database:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://user:123456@anteiku_kohi_database:5432/anteiku_kohi
      SECRET_KEY: seret_key
      HASH_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRES: 1440
      REFRESH_TOKEN_EXPIRES: 10080
    ports:
      - "8000:8000"
    volumes:
      - .:/src

volumes:
  postgres_data:
