services:
  anteiku_kohi_database:
    image: postgres:latest
    container_name: anteiku_kohi_database
    restart: unless-stopped
    env_file:
      - .env.database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s

  anteiku_kohi:
    build: .
    container_name: anteiku_kohi
    restart: unless-stopped
    depends_on:
      anteiku_kohi_database:
        condition: service_healthy
    env_file:
      - .env.app
    ports:
      - "8000:8000"
    volumes:
      - .:/src
      - meal_images:/public/images

volumes:
  postgres_data:
  meal_images:
